version: "3.9"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      target: development
    environment:
      APP_ENV: development
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: hiperautomacao_academy
      SECRET_KEY: dev-secret-key-change-me
      FRONTEND_URL: http://localhost:3000
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      ABACATEPAY_API_KEY: dev-sandbox-key
      ABACATEPAY_ENVIRONMENT: sandbox
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: development
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_URL: http://localhost:8000
      REACT_APP_DEFAULT_SUPPORT_URL: https://wa.me/5511999999999
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
  frontend-node-modules:
